# Generated by Django 4.0.4 on 2022-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_userinfo_depart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], verbose_name='支付状态'),
        ),
    ]
