# Generated by Django 4.0.4 on 2022-05-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=64, verbose_name='城市'),
        ),
    ]
